name: sonic
description: A fluent interface for handling network requests.
version: 0.0.2
homepage: https://github.com/ArunPrakashG/sonic

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  dio: ^4.0.6
  meta: ^1.8.0
  path: ^1.8.0
  synchronized: ^3.0.0+3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
