name: sonic
description: A fluent interface for handling network requests.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.6
  meta: ^1.8.0
  path: ^1.8.0
  synchronized: ^3.0.0+3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
